DEBUG 2014-02-05 16:18:14,077 btn_login_Click Of Login - Error :System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse)
   at Unirecruite.unirecruite.login.btn_login_Click(Object sender, ImageClickEventArgs e)
DEBUG 2014-02-05 16:44:57,296 ImageButton1_Click Of search - Error :System.NullReferenceException: Object reference not set to an instance of an object.
   at Unirecruite.unirecruite.search.UpdForOnlineTest()
   at Unirecruite.unirecruite.search.ImageButton1_Click(Object sender, ImageClickEventArgs e)
DEBUG 2014-02-05 16:46:02,218 sendMail Of search - Error :System.Web.HttpException: ?T?[?o?[?E?a?A?AÅe??M?O?A?h???X?a?ÅeÅhU?3?e?U?É ???B?T?[?o?[?c?c?IÅÒ?Åg??I???I?A?ÅN?e?A?ÅE?B451 <usinda.com> is invalid or DNS says does not exist
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException (0x8004020E): ?T?[?o?[?E?a?A?AÅe??M?O?A?h???X?a?ÅeÅhU?3?e?U?É ???B?T?[?o?[?c?c?IÅÒ?Åg??I???I?A?ÅN?e?A?ÅE?B451 <usinda.com> is invalid or DNS says does not exist

   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args, CultureInfo culture)
   at System.Web.Mail.SmtpMail.LateBoundAccessHelper.CallMethod(Type type, Object obj, String methodName, Object[] args)
   at System.Web.Mail.SmtpMail.LateBoundAccessHelper.CallMethod(Object obj, String methodName, Object[] args)
   --- End of inner exception stack trace ---
   at System.Web.Mail.SmtpMail.LateBoundAccessHelper.CallMethod(Object obj, String methodName, Object[] args)
   at System.Web.Mail.SmtpMail.CdoSysHelper.Send(MailMessage message)
   at System.Web.Mail.SmtpMail.Send(MailMessage message)
   at Unirecruite.unirecruite.search.sendMail(String StrTo, String userRollNo, String UserName, String userPassword, String subjectName, String TotalMarks, String PassingMarks, String TotalTime)
DEBUG 2014-02-05 18:09:53,312 btn_login_Click Of Login - Error :System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.End()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse)
   at Unirecruite.unirecruite.login.btn_login_Click(Object sender, ImageClickEventArgs e)
